config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'static_pages/index'
  get 'static_pages/about'

root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image_1, :image_2, :image_3, :tag)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def index
  @posts = Post.all
  end

  def about
@posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ritzblog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Rasa|Rubik+Mono+One" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </head>

  <body>
    <div id="wrapper">
        <div class="navigation">
        <div id="trapezoid">
        </div> 
      <div class="dropup">
        <button class="btn btn-primary dropdown-toggle" id="dropdown-button" type="button" data-toggle="dropdown">NAV
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu links-list">
        <li><%= link_to 'Home', static_pages_index_path %> </li>
         <li><%= link_to 'Add/Edit Posts', posts_path %> </li>
          <li><a href="http://ritz-site.bitballoon.com">See My Portfolio</a></li>
          <li><%= link_to 'About this Blog', static_pages_about_path %></li>
        </ul>
      </div>  
    </div>   
      <div class="content">    
         <%= yield %> 
      </div> 
      <div class="background">
        <div class="top-of-page-divs">
          <div class="corner1"></div>      
          <div class="site-title">B&nbsp;&nbsp;&nbsp;L&nbsp;&nbsp;O&nbsp;G</div>
        </div>
        <div class="dashes"></div>
      </div>
    </div>
  <div class="corner2"></div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div >
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image_1 %>
    <%= f.text_field :image_1 %>
  </div>

  <div class="field">
    <%= f.label :image_2 %>
    <%= f.text_field :image_2 %>
  </div>

  <div class="field">
    <%= f.label :image_3 %>
    <%= f.text_field :image_3 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Info</th>
      <th>Content</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @posts.each do |post| %>
      <tr>
        <td>
        Timestamp: <%= post.created_at %><br>
        Title: <%= post.title %><br> <br>
        Image 1: <%= post.image_1 %><br>
        Image 2: <%= post.image_2 %><br>
        Image 3: <%= post.image_3 %><br>
        Tag: <%= post.tag %><br> <br>
        </td>
        <td class="table-post-content"><%= post.content %></td>

        <td><%= link_to 'Show', post %><br>
        <%= link_to 'Edit', edit_post_path(post) %><br>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @post.created_at.to_date %> <br> <%= @post.title %>
</h2>
<div class="single-slider-holder">
<div class="single-slider">
  <div>
    <%= image_tag(@post.image_1, :class=>"single-slider-image") %>
  </div>
  <div>
    <%= image_tag(@post.image_2, :class=>"single-slider-image") %>
  </div>
    <div>
    <%= image_tag(@post.image_3, :class=>"single-slider-image") %>
  </div>
</div>
<div class="show-post-content">
  <div class="buttons-row">
  <button class="btn btn-default"><%= link_to 'Edit', edit_post_path(@post) %></button> 
  <button class="btn btn-default"><%= link_to 'Back', static_pages_index_path %></button>
  </div>
    <%= @post.content %>
</div>

app/views/static_pages/about.html.erb
<div class="show-post-content">
  <h1>About this Blog</h1>
  <%= image_tag(asset_path( 'me.jpg' ), :class=>"my-image") %>
  <h3>This blog is owned and managed by Ritz Wu (when she's not riding a ski lift), pictured above. The inspiration for the design was taken from Masayoshi Nakajo's poster, 'Mount Fuji: The Incurable Malady of Masayoshi Nakajo (cl: Creation Gallery G8)'. The link to the poster is <%= link_to 'here', "http://www.jagda.or.jp/en/awards/kamekura/05/" %>. All content written is original, all photos taken from the web and credited at the bottom of each post. </h3>
  <h3> If you have any questions you are welcome to contact me at <%= link_to 'ritz.wu@outlook.com', "ritz.wu@outlook.com" %>.</h3>
</div>

app/views/static_pages/index.html.erb
<h1 id="category">Art and Design</h1>
<div class="responsive">
    <% @posts.where(:tag => 'artdesign').each do |post| %>
    <div class="flex-post">
      <h3 class="post-title"><%= post.created_at.strftime("%d %B %Y") %> <br> <%= post.title %></h3> 
      <div class="landing-slider">
        <%= link_to image_tag(post.image_1, :class=>"slider-image"), polymorphic_url(post) %>
      </div>
      <div class="slider-preview-text">
      <%= post.content %>
      </div>
    </div>
    <% end %>
</div>

<h1 id="category">Web Development</h1>
<div class="responsive">
  <% @posts.where(:tag => 'webdev').each do |post| %>
    <div class="flex-post">
    <h3 class="post-title"><%= post.created_at.strftime("%d %B %Y") %> <br> <%= post.title %></h3> 
      <div class="landing-slider">
        <%= link_to image_tag(post.image_1, :class=>"slider-image"), polymorphic_url(post) %>
      </div>
      <div class="slider-preview-text">
      <%= post.content %>
      </div>
    </div>
    <% end %>
</div>

<h1 id="category">Life</h1>
<div class="responsive">
   <% @posts.where(:tag => 'life').each do |post| %>
    <div class="flex-post">
      <h3 class="post-title"><%= post.created_at.strftime("%d %B %Y") %> <br> <%= post.title %></h3> 
      <div class="landing-slider">
        <%= link_to image_tag(post.image_1, :class=>"slider-image"), polymorphic_url(post) %>
      </div>
      <div class="slider-preview-text">
       <%= post.content %>
      </div>
    </div>
  <% end %>
</div>